### ISSUE TITLE
XLS with 65535 rows causes 'numRows' to return 0

### ISSUE THREAD

**Issue by tomsie1000** [shuchkin/simplexls#7]
In the _parsesheet function, a count of the rows is gathered and set as the 'numRows' value in the returned object. If the number of rows is 65535, a row count of 0 is returned despite there being 65535 rows in the 'data' array. I found removing a single row from the data was enough to get it to work.

This code here returns 0 as the 'numRows' value:
![image](https://user-images.githubusercontent.com/37423151/99786943-0438b700-2b17-11eb-880a-0b267f13a470.png)

This causes the '->rows' method to never enter this for loop because the 'numRows' count is 0:
![image](https://user-images.githubusercontent.com/37423151/99787677-f46da280-2b17-11eb-920e-fec75b6be8cd.png)

I implemented a workaround by using count() on the ['cells'] property, if the count appears to be 0:
![image](https://user-images.githubusercontent.com/37423151/99787858-326ac680-2b18-11eb-85aa-df5e14173ccf.png)

Let me know if you want a copy of the offending file.

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexls] XLS with 65535 rows causes 'numRows' to return 0 (#7)



Hello, tomsie1000.

send me xls file





In the _parsesheet function, a count of the rows is gathered and set as the 'numRows' value in the returned object. If the number of rows is 65535, a row count of 0 is returned despite there being 65535 rows in the 'data' array. I found removing a single row from the data was enough to get it to work.
This code here returns 0 as the 'numRows' value:

This causes the '->rows' method to never enter this for loop because the 'numRows' count is 0:

I implemented a workaround by using count() on the ['cells'] property, if the count appears to be 0:

Let me know if you want a copy of the offending file.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by tomsie1000** [comment]
Thanks for the quick reply. I've mailed offending file to your address

**Comment by petrsimunek** [comment]
Hello, thanks @tomsie1000 for the workaround. I just faced the same issue. :-)

**Comment by shuchkin** [comment]
try 0.9.7

**Comment by tomsie1000** [comment]
Confirmed and issue has been solved. Thanks
